---

platform: linux

image_resource:
  type: docker-image
  source: { repository: maven, tag: 3.5.0-jdk-8-alpine }

inputs:
- name: SourceCode

outputs:
  - name: build

caches:
  - path: SourceCode/.m2

run:
  path: SourceCode/package.sh
